package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/richardimaoka/twitter-clone-2/gqlgen/graph/model"
)

// Tweet is the resolver for the tweet field.
func (r *queryResolver) Tweet(ctx context.Context) (*model.Tweet, error) {
	panic(fmt.Errorf("not implemented: Tweet - tweet"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
